apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatify

resources:
  - namespace.yaml
  - mongo.yaml
  - configmap.yaml
  - secret.yaml
  - app.yaml

labels:
  - pairs:
      app.kubernetes.io/name: chatify
      app.kubernetes.io/part-of: chatify
    includeSelectors: false

images:
  - name: chatify
    newName: chatify
    newTag: latest
